import Head from "next/head";
import {
  About,
  NavBar,
  Hero,
  HOC,
  Testamonials,
  Skills,
  Contact,
  Portfolio,
} from "../components";
import { urlFor } from "../lib/store";

export default function Home({
  home,
  about,
  portfolio,
  skill,
  experience,
  testamonial,
  contact,
  social
}) {
  const styles = {
    container: "max-w-[1400px] m-auto overflow-x-hidden",
  };
  const src = urlFor(home[0].image).url();
  return (
    <>
      <Head>
        <title>Bmk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/vercel.svg" />
      </Head>
      <div className="relative">
        {/* Nav Bar */}
        <div className="fixed top-0 left-0 right-0 z-30  bg-transparent backdrop-blur-lg shadow-l">
          <NavBar home={home} />
        </div>
        {/* Container */}
        <header
          id="head-back"
          style={{
            backgroundImage: `url(${src})`,
            backgroundRepeat: "no-repeat",
            backgroundSize: "cover",
            backgroundPosition: "center",
          }}
        >
          {/* Hero */}
          {/* <HOC id="home"> */}
          <Hero id="home" home={home} />
          {/* </HOC> */}
        </header>
        <main className={styles.container + ` overflow-hidden`}>
          {/* About */}
          <HOC social={social} id="about">
            <About about={about} />
          </HOC>
          {/* Portfolio */}
          <HOC social={social} id="portfolio">
            <Portfolio portfolio={portfolio} />
          </HOC>
          {/* Skills */}
          <HOC social={social} id="skills">
            <Skills skill={skill} experience={experience} />
          </HOC>
          {/* Testamonils */}
          <HOC social={social} id="testamonials">
            <Testamonials testamonial={testamonial} />
          </HOC>
          {/* Contact */}
          <HOC social={social} id="contact">
            <Contact contact={contact} />
          </HOC>
        </main>
        <footer className={styles.container + " flex flex-col justify-end items-end italic font-semibold text-xs text-blue uppercase "}>
          <p>&copy; 2022 bmk_energie</p>
          <p>All Right Reserved</p>
        </footer> 
      </div>
    </>
  );
}

export async function getStaticProps() {
  // ++++++++++++++++++++++++++++++++++++++++
  // about
  const queryAbout = encodeURIComponent(`*[_type == 'about']`);
  const urlAbout = `https://${process.env.sanity_project_id}.api.sanity.io/v2021-10-21/data/query/production?query=${queryAbout}`;
  let about = await fetch(urlAbout);
  about = await about.json();
  // ++++++++++++++++++++++++++++++++++++++++
  // home
  const queryHome = encodeURIComponent(`*[_type == 'home']{
    logo,
    image,
    title,
    yellowTitle,
    description,
    "cv": cv.asset->url
  }`);
  const urlHome = `https://${process.env.sanity_project_id}.api.sanity.io/v2021-10-21/data/query/production?query=${queryHome}`;
  let home = await fetch(urlHome);
  home = await home.json();
  // ++++++++++++++++++++++++++++++++++++++++
  // Portfolio
  const queryPortfolio = encodeURIComponent(`*[_type =='portfolio']{
    category,
    name,
    info,
    image
  }`);
  const urlPortfolio = `https://${process.env.sanity_project_id}.api.sanity.io/v2021-10-21/data/query/production?query=${queryPortfolio}`;
  let portfolio = await fetch(urlPortfolio);
  portfolio = await portfolio.json();
  // ++++++++++++++++++++++++++++++++++++++++
  // Skill
  const querySkill = encodeURIComponent(`*[_type == 'skill']{
    image,
    name
  }`);
  const urlSkill = `https://${process.env.sanity_project_id}.api.sanity.io/v2021-10-21/data/query/production?query=${querySkill}`;
  let skill = await fetch(urlSkill);
  skill = await skill.json();
  // ++++++++++++++++++++++++++++++++++++++++
  // Experience
  const queryExperience =
    encodeURIComponent(`*[_type=="experience"] | order(start asc){
    start,end, jobs[]{
       company, details, name
    }
  }`);
  const urlExp = `https://${process.env.sanity_project_id}.api.sanity.io/v2021-10-21/data/query/production?query=${queryExperience}`;
  let experience = await fetch(urlExp);
  experience = await experience.json();

  // ++++++++++++++++++++++++++++++++++++++++
  // Testamonial
  const queryTestamonal = encodeURIComponent(`*[_type=="testamonial"]{
      name, job, image, testamonial
    }`);
  const urltesta = `https://${process.env.sanity_project_id}.api.sanity.io/v2021-10-21/data/query/production?query=${queryTestamonal}`;
  let testamonial = await fetch(urltesta);
  testamonial = await testamonial.json();
  // ++++++++++++++++++++++++++++++++++++++++
  // conatct
  const queryContact = encodeURIComponent(`*[_type == "contact"]{
      tel, gmail
    }`);
  const urlcontact = `https://${process.env.sanity_project_id}.api.sanity.io/v2021-10-21/data/query/production?query=${queryContact}`;
  let contact = await fetch(urlcontact);
  contact = await contact.json();

  // social
  const querySocial = encodeURIComponent(`*[_type == "socialMedia"]{
      facebook, linkedIn, whatsapp, instagram
    }`);
  const urlSocial = `https://${process.env.sanity_project_id}.api.sanity.io/v2021-10-21/data/query/production?query=${querySocial}`;
  let social = await fetch(urlSocial);
  social = await social.json();

  return {
    props: {
      about: about.result,
      home: home.result,
      portfolio: portfolio.result,
      skill: skill.result,
      experience: experience.result,
      testamonial: testamonial.result,
      contact: contact.result,
      social: social.result,
    },
    revalidate: 10,
  };
}
